# Generated by Django 4.0.4 on 2022-06-26 03:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_timer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Timer',
        ),
        migrations.AddField(
            model_name='greenmember',
            name='a',
            field=models.CharField(default=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='greenmembers', to=settings.AUTH_USER_MODEL), max_length=200),
        ),
    ]
