# Generated by Django 4.0.4 on 2022-06-27 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_delete_timer_greenmember_a'),
    ]

    operations = [
        migrations.AddField(
            model_name='redmember',
            name='a',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='greenmember',
            name='a',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
