# Generated by Django 4.0.4 on 2022-06-27 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_redmember_a_alter_greenmember_a'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gc', models.IntegerField(default=0, null=True)),
                ('rc', models.IntegerField(default=0, null=True)),
            ],
        ),
    ]
